# IRE  MAJOR Project
# Contributors : Princu Jain & Arihant Gupta
# Extract Data from the URl's generated by twitter_url_extract.py

from boilerpipe.extract import Extractor
f=open('url_text.txt')
data=f.readlines()
f_o=open('url_data.txt','w')
for i in data:
	your_url=i.split('$')[0] #extracting unique URL's now
	extractor = Extractor(url=your_url)
	extracted_text = extractor.getText().encode('UTF-8')
	print extracted_text.replace("\n"," ").replace("\r"," ").replace("Play","").replace("now","").replace("next","").replace("  ","")

#your_url='https://www.youtube.com/watch?&v=1cfNYdO--RA'
#extractor = Extractor(url=your_url)
#extracted_text = extractor.getText().encode('UTF-8')
	
